
# STRING CLEANING



String cleaning is the process of **standardizing text data and removing unwanted characters, spaces, or formatting**.

Main techniques:

1. Regular Expressions
2. Whitespace Removal
3. Case Normalization
4. Special Character Removal
5. String Replacement and Extraction
6. Cleaning Before Datatype Conversion

---

# 1. REGULAR EXPRESSIONS (REGEX)

**Regex (Regular Expression)** is used for **pattern matching and text manipulation**.

Common Regex patterns:

| Pattern | Meaning |
|---|---|
| `\d` | Digit |
| `\D` | Non-digit |
| `\w` | Word character |
| `\W` | Non-word character |
| `\s` | Whitespace |
| `\S` | Non-whitespace |
| `.` | Any character |
| `+` | One or more |
| `*` | Zero or more |
| `?` | Zero or one |
| `^` | Start of string |
| `$` | End of string |
| `[]` | Character set |
| `()` | Capture group |

Example:

```python
r"\d+"
````

This matches **one or more digits**.

Example:

```text
"Age: 25"
```

`r"\d+"` matches:

```text
25
```

---

# 2. WHITESPACE REMOVAL

## Remove Leading and Trailing Spaces

Use `.str.strip()`:

```python
df["Name"] = df["Name"].str.strip()
```

Example:

```text
"  Arun Kumar  "
```

↓

```text
"Arun Kumar"
```

---

## Remove Leading Spaces

Use `.str.lstrip()`:

```python
df["Name"] = df["Name"].str.lstrip()
```

---

## Remove Trailing Spaces

Use `.str.rstrip()`:

```python
df["Name"] = df["Name"].str.rstrip()
```

---

## Remove Multiple Spaces Between Words

Use Regex:

```python
df["Name"] = df["Name"].str.replace(
    r"\s+",
    " ",
    regex=True
)
```

Example:

```text
"Arun    Kumar"
```

↓

```text
"Arun Kumar"
```

### Complete Whitespace Cleaning

```python
df["Name"] = (
    df["Name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)
```

---

# 3. CASE NORMALIZATION

Case normalization makes text follow a consistent capitalization format.

## Lowercase

```python
df["City"] = df["City"].str.lower()
```

Example:

```text
"CHENNAI"
```

↓

```text
"chennai"
```

---

## Uppercase

```python
df["City"] = df["City"].str.upper()
```

Example:

```text
"chennai"
```

↓

```text
"CHENNAI"
```

---

## Capitalize

```python
df["Name"] = df["Name"].str.capitalize()
```

Example:

```text
"ARUN KUMAR"
```

↓

```text
"Arun kumar"
```

---

## Title Case

```python
df["Name"] = df["Name"].str.title()
```

Example:

```text
"arun kumar"
```

↓

```text
"Arun Kumar"
```

### When to Use

For categorical values, lowercase is often useful for standardization:

```text
Chennai
CHENNAI
chennai
```

↓

```text
chennai
chennai
chennai
```

For names, title case is often more readable.

---

# 4. SPECIAL CHARACTER REMOVAL

## Remove Everything Except Letters and Whitespace

```python
df["Name"] = df["Name"].str.replace(
    r"[^a-zA-Z\s]",
    "",
    regex=True
)
```

Example:

```text
"Arun@123 Kumar!"
```

↓

```text
"Arun Kumar"
```

---

## Remove Everything Except Digits

Use `\D`:

```python
df["Phone"] = df["Phone"].str.replace(
    r"\D",
    "",
    regex=True
)
```

Example:

```text
"+91-98765-43210"
```

↓

```text
"919876543210"
```

This is useful when phone numbers contain spaces, hyphens, brackets, or other formatting characters.

---

# 5. CURRENCY CLEANING

Example:

```text
₹30,000
₹45,000
₹50,000
```

Remove the currency symbol and commas:

```python
df["Price"] = df["Price"].str.replace(
    r"[₹,]",
    "",
    regex=True
)
```

Result:

```text
30000
45000
50000
```

Then convert to a numerical datatype:

```python
df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)
```

Now the values can be used for numerical calculations.

---

# 6. STRING REPLACE

`.str.replace()` can replace specific text.

Example:

```python
df["City"] = df["City"].str.replace(
    "Madras",
    "Chennai",
    regex=False
)
```

This changes:

```text
Madras
```

to:

```text
Chennai
```

It can also be used with Regex patterns:

```python
df["Name"] = df["Name"].str.replace(
    r"\d+",
    "",
    regex=True
)
```

This removes digits from the string.

---

# 7. REGEX `replace()` VS `extract()`

## `replace()`

Used to **remove or replace unwanted text**.

Example:

```python
df["Name"] = df["Name"].str.replace(
    r"\d+",
    "",
    regex=True
)
```

---

## `extract()`

Used to **extract specific information from a string using a pattern**.

Example:

```python
df["Domain"] = df["Email"].str.extract(
    r"@(.+)"
)
```

For:

```text
user@gmail.com
```

Result:

```text
gmail.com
```

---

# 8. COMPLETE STRING CLEANING PIPELINE

Raw value:

```text
"  ARUN!!!    KUMAR  "
```

Clean it using:

```python
df["Name"] = (
    df["Name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.replace(r"[^a-zA-Z\s]", "", regex=True)
    .str.title()
)
```

Result:

```text
"Arun Kumar"
```

### Cleaning Steps

```text
Raw String
    ↓
Remove leading/trailing spaces
    ↓
Remove extra spaces
    ↓
Remove unwanted characters
    ↓
Standardize case
    ↓
Clean String
```

---

# 9. STRING CLEANING BEFORE DATATYPE CONVERSION

String cleaning is often required before converting a column to a numerical or datetime datatype.

Example:

```text
" ₹30,000 "
```

First clean the string:

```text
"30000"
```

Then convert the datatype:

```python
df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)
```

Result:

```text
30000.0
```

### General Workflow

```text
Raw Data
   ↓
Clean
   ↓
Standardize
   ↓
Validate
   ↓
Convert Datatype
```

---

# IMPORTANT RULES

* Use `.str.strip()` to remove leading and trailing whitespace.
* Use `.str.replace()` for replacing or removing unwanted text.
* Use Regex when the unwanted text follows a pattern.
* Use `.str.lower()` or `.str.upper()` for consistent categorical values.
* Use `.str.title()` when title case is appropriate for text such as names.
* Clean currency symbols and separators before numerical conversion.
* Use `errors="coerce"` when invalid values should become missing values.
* Do not remove characters blindly; determine whether they contain useful information.
* Always consider the meaning of the data before cleaning.

---

# 🧠 Key Idea

> **Clean → Standardize → Validate → Convert Datatype**

String cleaning makes text **consistent, usable, and ready for further data analysis or machine learning.**

```
```

| Pattern | Meaning              |
| ------- | -------------------- |
| `\d`    | Digit                |
| `\D`    | Not a digit          |
| `\w`    | Word character       |
| `\W`    | Not a word character |
| `\s`    | Whitespace           |
| `\S`    | Not whitespace       |
| `.`     | Any character        |
| `+`     | One or more          |
| `*`     | Zero or more         |
| `?`     | Zero or one          |
| `^`     | Start of string      |
| `$`     | End of string        |
| `[]`    | Character set        |
| `()`    | Capture group        |

In [55]:
import pandas as pd

data = {
    "Name": [
        "  ARUN!!! ",
        "Priya   Kumar",
        "  kumar@@@ ",
        "MEENA###",
        " Ravi "
    ],

    "City": [
        " chennai ",
        "CHENNAI",
        "Madras",
        " madurai ",
        "MADURAI"
    ],

    "Phone": [
        "+91-98765-43210",
        "98765 43211",
        "+91 98765 43212",
        "98765-43213",
        "+91-98765-43214"
    ],

    "Price": [
        "₹30,000",
        "₹45,500",
        "₹1,20,000",
        "₹55,000",
        "₹75,500"
    ],

    "Email": [
        "arun@gmail.com",
        "priya@yahoo.com",
        "kumar@outlook.com",
        "meena@gmail.com",
        "ravi@company.in"
    ]
}

df = pd.DataFrame(data)
df

            Name       City            Phone      Price              Email
0       ARUN!!!    chennai   +91-98765-43210    ₹30,000     arun@gmail.com
1  Priya   Kumar    CHENNAI      98765 43211    ₹45,500    priya@yahoo.com
2      kumar@@@      Madras  +91 98765 43212  ₹1,20,000  kumar@outlook.com
3       MEENA###   madurai       98765-43213    ₹55,000    meena@gmail.com
4          Ravi     MADURAI  +91-98765-43214    ₹75,500    ravi@company.in

In [56]:
df['Name'] = df['Name'].str.strip()

In [57]:
df['Name'] = df['Name'].str.replace(r'[^a-zA-Z\s]','',regex = True)

In [58]:
df

            Name       City            Phone      Price              Email
0           ARUN   chennai   +91-98765-43210    ₹30,000     arun@gmail.com
1  Priya   Kumar    CHENNAI      98765 43211    ₹45,500    priya@yahoo.com
2          kumar     Madras  +91 98765 43212  ₹1,20,000  kumar@outlook.com
3          MEENA   madurai       98765-43213    ₹55,000    meena@gmail.com
4           Ravi    MADURAI  +91-98765-43214    ₹75,500    ravi@company.in

In [59]:
df['Name'] = df['Name'].str.title()
df["Name"] = df["Name"].str.replace(r"\s+"," ",regex=True)

In [60]:
df

          Name       City            Phone      Price              Email
0         Arun   chennai   +91-98765-43210    ₹30,000     arun@gmail.com
1  Priya Kumar    CHENNAI      98765 43211    ₹45,500    priya@yahoo.com
2        Kumar     Madras  +91 98765 43212  ₹1,20,000  kumar@outlook.com
3        Meena   madurai       98765-43213    ₹55,000    meena@gmail.com
4         Ravi    MADURAI  +91-98765-43214    ₹75,500    ravi@company.in

In [61]:
df['City'] = df['City'].str.title().str.strip()

In [62]:
df['City'] = df['City'].str.replace('Madras','Chennai',regex = False)

In [63]:
df['City']

0    Chennai
1    Chennai
2    Chennai
3    Madurai
4    Madurai
Name: City, dtype: str

In [64]:
df["Phone"] = df["Phone"].str.strip()
df["Phone"] = df["Phone"].str.replace(r"\D","",regex=True)

In [65]:
df['Phone']

0    919876543210
1      9876543211
2    919876543212
3      9876543213
4    919876543214
Name: Phone, dtype: str

In [66]:
df['Phone'] = df['Phone'].str.replace(r'^91','', regex = True)

In [67]:
df['Phone']

0    9876543210
1    9876543211
2    9876543212
3    9876543213
4    9876543214
Name: Phone, dtype: str

In [68]:
df['Price'] = df['Price'].str.strip()

In [69]:
df['Price']

0      ₹30,000
1      ₹45,500
2    ₹1,20,000
3      ₹55,000
4      ₹75,500
Name: Price, dtype: str

In [70]:
df['Price'] = df['Price'].str.replace(r'[₹,]','',regex = True)

In [71]:
df['Price'] = df['Price'].astype('int')

In [51]:
df['Price']

0     30000
1     45500
2    120000
3     55000
4     75500
Name: Price, dtype: int64

In [52]:
df["Domain"] = df["Email"].str.extract(
    r"@(.+)"
)

In [53]:
df

          Name     City       Phone   Price              Email       Domain
0         Arun  Chennai  9876543210   30000     arun@gmail.com    gmail.com
1  Priya Kumar  Chennai  9876543211   45500    priya@yahoo.com    yahoo.com
2        Kumar  Chennai  9876543212  120000  kumar@outlook.com  outlook.com
3        Meena  Madurai  9876543213   55000    meena@gmail.com    gmail.com
4         Ravi  Madurai  9876543214   75500    ravi@company.in   company.in

In [54]:
df.dtypes

Name        str
City        str
Phone       str
Price     int64
Email       str
Domain      str
dtype: object