# DATA VALIDATION

Data validation means checking whether data satisfies **predefined requirements and rules** before it is accepted, analyzed, or used in a data/ML pipeline.

### Basic Workflow

```text
Raw Data
   ↓
Validation Rules
   ↓
Valid → Accept
Invalid → Flag / Reject / Correct
````

---

# 1. CONSTRAINTS

A **constraint** is a rule that a value must satisfy.

Common constraints:

1. Range
2. Data Type
3. Uniqueness
4. Non-null
5. Allowed Values

---

## Range Constraint

A range constraint checks whether a numerical value falls within an expected range.

Example:

**Age must be between 0 and 100.**

```python
df["Age"].between(0, 100)
```

This returns `True` for valid values and `False` for invalid values.

### Find Invalid Values

```python
df[
    ~df["Age"].between(0, 100)
]
```

---

## Data Type Constraint

A data type constraint checks whether a column has the expected datatype.

Example:

```text
Age        → Integer
Salary     → Numeric
Date       → Datetime
Name       → String
Active     → Boolean
```

Check actual datatypes:

```python
df.dtypes
```

The actual datatype should match the expected datatype defined by the dataset schema.

---

## Uniqueness Constraint

A uniqueness constraint checks whether a column contains duplicate values when the column is expected to be unique.

Example:

**Customer_ID must be unique.**

```python
df["Customer_ID"].is_unique
```

Result:

```text
True  → All values are unique
False → Duplicate values exist
```

---

## Non-null Constraint

A non-null constraint checks whether a required column contains missing values.

Example:

**Customer_ID cannot be missing.**

```python
df["Customer_ID"].notna().all()
```

Result:

```text
True  → No missing values
False → Missing values exist
```

---

## Allowed Value Constraint

An allowed-value constraint checks whether values belong to a predefined set of valid categories.

Example:

**Gender can only be Male or Female.**

```python
df["Gender"].isin(
    ["Male", "Female"]
)
```

### Find Invalid Values

```python
df[
    ~df["Gender"].isin(
        ["Male", "Female"]
    )
]
```

---

# 2. BUSINESS RULES

**Business rules** describe logical conditions based on how a business or system operates.

They often involve **multiple columns**.

Example:

**If Age < 18, License must be "No".**

```python
invalid = df[
    (df["Age"] < 18) &
    (df["License"] == "Yes")
]
```

The rows returned by `invalid` violate the business rule.

### Other Examples

```text
Experience >= 10
        ↓
Salary should be >= 50000
```

```text
Premium Customer
        ↓
Discount <= 30%
```

```text
Cancelled Order
        ↓
Payment Status must follow the company's refund rule
```

Business rules depend on the **specific domain and business requirements**.

---

# CONSTRAINT VS BUSINESS RULE

| Constraint                                    | Business Rule                                         |
| --------------------------------------------- | ----------------------------------------------------- |
| Defines what values are allowed               | Defines whether the data makes logical/business sense |
| Usually focuses on a column or basic property | Often involves multiple columns                       |
| More general                                  | Domain-specific                                       |
| Example: Age must be 0–100                    | Example: Age < 18 → License = No                      |

### Simple Difference

**Constraint:**

> "What values are allowed?"

Example:

```text
Age must be between 0 and 100.
```

**Business Rule:**

> "Does the data make sense according to the business?"

Example:

```text
Age < 18 → License = No
```

---

# 3. SCHEMA VALIDATION

A **schema** is a blueprint that describes what a dataset should look like.

A schema can define:

* Column names
* Data types
* Required columns
* Nullable/non-nullable columns
* Allowed values
* Expected structure

Example:

| Column      | Type     | Required |
| ----------- | -------- | -------- |
| Customer_ID | Integer  | Yes      |
| Name        | String   | Yes      |
| Age         | Integer  | Yes      |
| Salary      | Float    | Yes      |
| Join_Date   | Datetime | Yes      |
| Active      | Boolean  | No       |

---

## Required Columns

Define the columns that must exist:

```python
required = [
    "Customer_ID",
    "Name",
    "Age",
    "Salary",
    "Join_Date"
]
```

Find missing required columns:

```python
missing = set(required) - set(df.columns)
```

If:

```text
missing = set()
```

then all required columns exist.

If the set contains column names, those required columns are missing.

---

## Datatype Validation

Check the actual datatypes:

```python
df.dtypes
```

Compare the actual datatypes with the expected schema.

Example:

```text
Expected:
Age → integer

Actual:
Age → object
```

This indicates a datatype mismatch that should be investigated and corrected if necessary.

---

## Required Values

Check that required values are not missing:

```python
df["Customer_ID"].notna().all()
```

---

## Allowed Values

Example:

**Active can only be `True` or `False`.**

```python
df["Active"].isin(
    [True, False]
).all()
```

---

## Range Validation

Example:

**Age must be between 0 and 100.**

```python
df["Age"].between(0, 100).all()
```

Result:

```text
True  → All values satisfy the rule
False → At least one value violates the rule
```

---

# VALIDATION TYPES

| Validation     | Example                                 |
| -------------- | --------------------------------------- |
| Range          | Age must be 0–100                       |
| Data Type      | Age must be Integer                     |
| Uniqueness     | Customer_ID must be unique              |
| Non-null       | Customer_ID cannot be missing           |
| Allowed Values | Gender must be Male/Female              |
| Business Rule  | Age < 18 → License = No                 |
| Schema         | Required columns and expected datatypes |

---

# SCHEMA VALIDATION IN PRODUCTION

Schema validation can automatically check incoming datasets before they enter a **data or machine-learning pipeline**.

### Concept

```text
Incoming Data
      ↓
Schema Validation
      ↓
   ┌──┴──┐
 Valid  Invalid
   ↓       ↓
Continue  Reject / Alert
```

This helps prevent incorrect data from entering downstream systems.

### Common Python Libraries

* **Pandera**
* **Great Expectations**
* **Pydantic**

Only the basic concept is required at this stage.

---

# IMPORTANT

Data validation is different from data cleaning.

**Data Cleaning:**

> Fix or transform problematic data.

**Data Validation:**

> Check whether data satisfies predefined rules.

Typical workflow:

```text
Raw Data
   ↓
Data Cleaning
   ↓
Data Validation
   ↓
Valid Data
   ↓
Analysis / Machine Learning
```

In production pipelines, validation can also happen **before and after cleaning**, depending on the requirements.

---

# 🧠 KEY IDEA

> **Data Validation = Check whether data follows predefined rules before trusting or using it.**

```text
Constraints
   +
Business Rules
   +
Schema Validation
   ↓
Reliable Data
```

```
```

In [33]:
import pandas as pd
data = {
    "Customer_ID": [101, 102, 103, 104, 104],
    "Name": ["Arun", "Priya", "Kumar", "Meena", "Ravi"],
    "Age": [25, 17, 35, 150, 28],
    "Salary": [40000, 30000, -5000, 60000, 45000],
    "License": ["Yes", "Yes", "Yes", "Yes", "No"],
    "Customer_Type": [
        "Regular",
        "Premium",
        "Premium",
        "Regular",
        "Regular"
    ],
    "Discount": [5, 40, 20, 10, 5]
}

df = pd.DataFrame(data)

In [34]:
df

   Customer_ID   Name  Age  Salary License Customer_Type  Discount
0          101   Arun   25   40000     Yes       Regular         5
1          102  Priya   17   30000     Yes       Premium        40
2          103  Kumar   35   -5000     Yes       Premium        20
3          104  Meena  150   60000     Yes       Regular        10
4          104   Ravi   28   45000      No       Regular         5

In [35]:
df = df.drop(df[~df['Age'].between(0,100)].index)

In [37]:
df = df.drop(df[~df['Salary']>0].index)

In [38]:
df.dtypes

Customer_ID      int64
Name               str
Age              int64
Salary           int64
License            str
Customer_Type      str
Discount         int64
dtype: object

In [39]:
df = df.drop(df[((df['Customer_Type'] == 'Premium') & (df['Discount'] >30 ))].index)

In [40]:
df

   Customer_ID  Name  Age  Salary License Customer_Type  Discount
0          101  Arun   25   40000     Yes       Regular         5
4          104  Ravi   28   45000      No       Regular         5